name: 'Automatic Build on Schedule'
on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  continuous-delivery:
    runs-on: ubuntu-20.04

    steps:
        - uses: actions/checkout@v2

        - name: Setting up Python Environment
          uses: actions/setup-python@v2
          with:
              python-version: '3.8'
              architecture: 'x64'

        - name: Install Python Dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Submodule Init for Data
          run: |
            git submodule update --init --remote --depth 1

        - name: Build Pages Json Data
          run: |
            python DataPreprocessing.py

        - name: Add CNAME
          run: echo "wear-a-mask.mijazz.icu" > pages/CNAME

        - name: Generate Sitemap for search engine
          id: sitemap
          uses: cicirello/generate-sitemap@v1.6.2
          with:
            base-url-path: https://wear-a-mask.mijazz.icu/
            path-to-root: pages
            sitemap-format: xml

        - name: Deploy to Pages
          uses: s0/git-publish-subdir-action@develop
          env:
            REPO: self
            BRANCH: gh-pages
            FOLDER: pages
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SQUASH_HISTORY: true
            SKIP_EMPTY_COMMIT: true
            MESSAGE: 'Schedule Update'
